import hashlib
from core import models


def build_sample_unique_id(seq_id, collecting_id, submit_inst, colect_inst) -> str:
    """Return the expected sample unique id given its 4 components."""
    combined = f"{seq_id or ''}|{collecting_id}|{submit_inst}|{colect_inst}".lower()
    return hashlib.sha256(combined.encode()).hexdigest()


def create_sample_unique_id(sample_payload: dict) -> str:
    # Generates a deterministic sample_unique_id from required fields.
    # NOTE: Required-field validation is handled in the serializer.
    seq_id = sample_payload.get("sequencing_sample_id")
    colect_isolate_id = sample_payload.get("collecting_lab_isolate_id")
    colect_sample_id = sample_payload.get("collecting_lab_sample_id")
    submit_inst = sample_payload.get("submitting_institution")
    colect_inst = sample_payload.get("collecting_institution")

    # anyOf semantics: prioritize isolate_id; fallback to sample_id if missing.
    collecting_id = colect_isolate_id or colect_sample_id
    if not collecting_id:
        raise ValueError(
            "One of collecting_lab_isolate_id or collecting_lab_sample_id is required"
        )

    fingerprint = build_sample_unique_id(
        seq_id, collecting_id, submit_inst, colect_inst
    )
    max_length = models.Sample._meta.get_field("sample_unique_id").max_length
    return fingerprint[:max_length]


def get_existing_sample(sample_payload: dict):
    normalized_id = create_sample_unique_id(sample_payload)
    return models.Sample.objects.filter(sample_unique_id=normalized_id).last()


def prepare_sample_create(sample_payload: dict):
    if "sample_unique_id" in sample_payload and sample_payload["sample_unique_id"]:
        raise ValueError("sample_unique_id is generated by the API")
    normalized_id = create_sample_unique_id(sample_payload)
    if models.Sample.objects.filter(sample_unique_id=normalized_id).exists():
        raise ValueError("Sample already exists")

    schema_name = sample_payload.get("schema_name")
    schema_version = sample_payload.get("schema_version")
    if isinstance(schema_name, str):
        schema_name = schema_name.strip()
    if isinstance(schema_version, str):
        schema_version = schema_version.strip()
    if not schema_name or not schema_version:
        raise ValueError("schema_name and schema_version are required")
    schema_obj = models.Schema.objects.filter(
        schema_name=schema_name, schema_version=schema_version
    ).last()
    if schema_obj is None:
        raise ValueError(
            f"Schema not found for name={schema_name} version={schema_version}"
        )

    defaults = {}
    sample_field_names = {
        f.name
        for f in models.Sample._meta.get_fields()
        if getattr(f, "is_relation", False) is False
    }
    excluded_defaults = {"id", "sample_unique_id", "created_at"}
    for key, value in sample_payload.items():
        if key in excluded_defaults or key not in sample_field_names:
            continue
        if value is None:
            continue
        if isinstance(value, str):
            trimmed = value.strip()
            if not trimmed:
                continue
            defaults[key] = trimmed
        else:
            defaults[key] = value

    return {
        "sample_unique_id": normalized_id,
        "schema_obj": schema_obj,
        "defaults": defaults,
    }
