## According to black coding style: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
[flake8]
max-line-length = 88

select = C,E,F,W,B,B950
extend-ignore = E203, E501, W503, W605
exclude =
    .git,
    __pycache__,
    .venv,
    build,
    dist,
    dummy,
    docs,
    conf,
    **/migrations/*
filename = core/*.py, core/**/*.py
