# Generated by Django 4.2.15 on 2026-03-16 11:12

from django.db import migrations, models


def cleanup_legacy_core_objects(apps, schema_editor):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        constraints_by_table = {
            table_name: connection.introspection.get_constraints(cursor, table_name)
            for table_name in connection.introspection.table_names(cursor)
        }
    existing_tables = set(constraints_by_table.keys())

    def drop_table_if_exists(table_name):
        if table_name in existing_tables:
            schema_editor.execute(
                "DROP TABLE {table}".format(
                    table=schema_editor.quote_name(table_name),
                )
            )
            existing_tables.remove(table_name)

    lineagefields_model = apps.get_model("core", "LineageFields")
    table_name = "core_metadata_values"
    index_names = [
        "core_metada_group_i_bc41e7_idx",
        "core_metada_schema__65c2ab_idx",
        # This was previously created by db_index=True on MetadataValues.value.
        "core_metadata_values_value_bfb8351c",
        # Defensive cleanup for manual performance-index iterations.
        "idx_core_mv_value",
        "idx_core_mv_prop_value",
    ]

    constraints = constraints_by_table.get(table_name, {})

    for index_name in index_names:
        constraint = constraints.get(index_name)
        if constraint and constraint.get("index"):
            schema_editor.execute(
                "DROP INDEX {idx} ON {table}".format(
                    idx=schema_editor.quote_name(index_name),
                    table=schema_editor.quote_name(table_name),
                )
            )

    # These tables belonged to legacy variant/lineage modules that no longer
    # exist in the current codebase. Some installations already deleted part of
    # this schema manually, so cleanup must be idempotent.
    legacy_tables = [
        apps.get_model("core", "VariantAnnotation")._meta.db_table,
        apps.get_model("core", "VariantInSample")._meta.db_table,
        apps.get_model("core", "Variant")._meta.db_table,
        apps.get_model("core", "OrganismAnnotation")._meta.db_table,
        apps.get_model("core", "Gene")._meta.db_table,
        apps.get_model("core", "LineageValues")._meta.db_table,
        lineagefields_model._meta.get_field("schemaID").remote_field.through._meta.db_table,
        apps.get_model("core", "LineageInfo")._meta.db_table,
        lineagefields_model._meta.db_table,
        apps.get_model("core", "Effect")._meta.db_table,
        apps.get_model("core", "Filter")._meta.db_table,
        apps.get_model("core", "Chromosome")._meta.db_table,
    ]

    for legacy_table in legacy_tables:
        drop_table_if_exists(legacy_table)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metadatavalues_core_metada_schema__6d30fa_idx'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    cleanup_legacy_core_objects,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='gene',
                    name='chromosomeID',
                ),
                migrations.RemoveField(
                    model_name='gene',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='lineagefields',
                    name='schemaID',
                ),
                migrations.DeleteModel(
                    name='LineageInfo',
                ),
                migrations.RemoveField(
                    model_name='lineagevalues',
                    name='lineage_fieldID',
                ),
                migrations.RemoveField(
                    model_name='organismannotation',
                    name='chromosomeID',
                ),
                migrations.RemoveField(
                    model_name='organismannotation',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='variant',
                    name='chromosomeID_id',
                ),
                migrations.RemoveField(
                    model_name='variant',
                    name='filterID_id',
                ),
                migrations.RemoveField(
                    model_name='variantannotation',
                    name='effectID_id',
                ),
                migrations.RemoveField(
                    model_name='variantannotation',
                    name='geneID_id',
                ),
                migrations.RemoveField(
                    model_name='variantannotation',
                    name='variantID_id',
                ),
                migrations.RemoveField(
                    model_name='variantinsample',
                    name='sampleID_id',
                ),
                migrations.RemoveField(
                    model_name='variantinsample',
                    name='variantID_id',
                ),
                migrations.RemoveIndex(
                    model_name='metadatavalues',
                    name='core_metada_group_i_bc41e7_idx',
                ),
                migrations.RemoveIndex(
                    model_name='metadatavalues',
                    name='core_metada_schema__65c2ab_idx',
                ),
                migrations.AlterField(
                    model_name='metadatavalues',
                    name='value',
                    field=models.CharField(blank=True, max_length=240, null=True),
                ),
                migrations.DeleteModel(
                    name='Chromosome',
                ),
                migrations.DeleteModel(
                    name='Effect',
                ),
                migrations.DeleteModel(
                    name='Filter',
                ),
                migrations.DeleteModel(
                    name='Gene',
                ),
                migrations.DeleteModel(
                    name='LineageFields',
                ),
                migrations.DeleteModel(
                    name='LineageValues',
                ),
                migrations.DeleteModel(
                    name='OrganismAnnotation',
                ),
                migrations.DeleteModel(
                    name='Variant',
                ),
                migrations.DeleteModel(
                    name='VariantAnnotation',
                ),
                migrations.DeleteModel(
                    name='VariantInSample',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema_default',
            field=models.BooleanField(default=False),
        ),
    ]
