# Generated by Django 4.2.15 on 2026-03-25 12:00

from django.db import migrations, models


def backfill_sample_fingerprint(apps, schema_editor):
    Sample = apps.get_model("core", "Sample")
    for sample in (
        Sample.objects.filter(fingerprint__isnull=True)
        .exclude(sample_unique_id="")
        .iterator()
    ):
        sample.fingerprint = sample.sample_unique_id
        sample.save(update_fields=["fingerprint"])


def create_sample_id_sequence(apps, schema_editor):
    SampleIdSequence = apps.get_model("core", "SampleIdSequence")
    SampleIdSequence.objects.get_or_create(
        sequence_name="sample_unique_id",
        defaults={"last_value": ""},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_gene_chromosomeid_remove_gene_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name="SampleIdSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_name", models.CharField(max_length=40, unique=True)),
                ("last_value", models.CharField(blank=True, default="", max_length=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_sample_id_sequence",
            },
        ),
        migrations.RunPython(
            backfill_sample_fingerprint,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_sample_id_sequence,
            migrations.RunPython.noop,
        ),
    ]
