## NOTE: WSGISocketPrefix,WSGIPythonHome, WSGIScriptAlias and WSGIPythonPath cannot occur within <VirtualHost> section

# Path to serve your app at and wsgi script path

<VirtualHost *:80>
    ServerAdmin bioinformatica@isciii.es
    ServerName pathocore-api.isciiides.es
    DocumentRoot /opt/pathocore-api


    ## Load wsgi module with library associated in virtualenv
    LoadModule wsgi_module "/opt/pathocore-api/virtualenv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-x86_64-linux-gnu.so"

    WSGIDaemonProcess pathocore-api.isciiides.es python-home=/opt/pathocore-api/virtualenv python-path=/opt/pathocore-api
    WSGIProcessGroup pathocore-api.isciiides.es
    WSGIScriptAlias / /opt/pathocore-api/pathocore_api/wsgi.py
    WSGIPassAuthorization On
    WSGIApplicationGroup %{GLOBAL}

    # Directory piece. This ensures that apache can access wsgi.py script.
    <Directory /opt/pathocore-api/pathocore_api>
        <Files wsgi.py>
            Satisfy Any
            Allow from all
        </Files>
    </Directory>

    Alias /static /opt/pathocore-api/static

    <Directory /opt/pathocore-api/static>
        Satisfy Any
        Allow from all
    </Directory>

    Alias /documents /opt/pathocore-api/documents

    <Directory /opt/pathocore-api/documents>
        Satisfy Any
        Allow from all
    </Directory>

    ErrorLog logs/pathocore-api.isciiides.es-apache.error.log
    CustomLog logs/pathocore-api.isciiides.es-apache.access.log combined env=!forwarded
    CustomLog logs/pathocore-api.isciiides.es-apache.access.log proxy env=forwarded

</VirtualHost>
